package ch.uzh.ifi.seal.soprafs15.group_00_android.models;

import android.os.Parcelable;

import auto.parcel.AutoParcel;
import ch.uzh.ifi.seal.soprafs15.group_00_android.models.gson.AutoGson;

@AutoParcel @AutoGson
public abstract class User implements Parcelable {

    // AutoParcel / AutoGson demand abstract dummy methods, getter/setter get autogenerated upon build.
    public abstract String name();
    public abstract String username();

    public static User create(String name, String username) {
        return new AutoParcel_User(name, username);
    }

}

